/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniFact */

#ifndef _Included_JniFact
#define _Included_JniFact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniFact
 * Method:    calculate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_JniFact_calculate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
